---
- name: Start {{ docker_name }} docker container
  docker_container:
    name: '{{ docker_name }}'
    image: '{{ docker_image }}'
    ports:
      - '{{ port }}:80'
    restart_policy: 'unless-stopped'
    pull: '{{ pull_image }}'
    env:
      ROS_MASTER_URI: '{{ ros_master_uri }}'
      ROS_IP: '{{ ros_ip }}'
  register: container_status
